### ISSUE TITLE
Warning : deprecated way to define scene

### ISSUE THREAD

**Issue by CozmoCyke** [badernageral/colobot-logic#2]
I try the colobot-logic level ,

[INFO]: Loading level: levels/custom/chapter001/level003/scene.txt
[WARN]: This level is using deprecated way of defining %1$s scene. Please change the %1$s= parameter in EndingFile from %2$d to "levels/other/%1$s%2$03d.txt".
[WARN]: This level is using deprecated way of defining %1$s scene. Please change the %1$s= parameter in EndingFile from %2$d to "levels/other/%1$s%2$03d.txt".

scene.txt contained this file:
EndingFile win=2 lost=0

I don't understand what I have to change to avoid the deprecated way !
Windows 10 , Colobot Gold , official 0.1.12-alpha build

I try one solution but it doesn't change the warning message :-(

EndingFile win=2 lost=0
by
EndingFile win=002 lost=0

**Comment by badernageral** [comment]
Hi @CozmoCyke , this error does not affect the missions, however I alheady fix it, you can now download the corrected code.

**Comment by CozmoCyke** [comment]
Thank you again.
We can now close this issue

**Comment by CozmoCyke** [comment]
The new syntax has been used (replace number by file name with path)
