### ISSUE TITLE
Error opening file with PHYSFS (chapter 1 mission 3)

### ISSUE THREAD

**Issue by CozmoCyke** [badernageral/colobot-logic#3]
[ERROR]: Error opening file with PHYSFS: "textures/shadow00.png"
[ERROR]: Couldn't load texture 'textures/shadow00.png': Unable to open file, blacklisting
[ERROR]: Error opening file with PHYSFS: "textures/shadow01.png"
[ERROR]: Couldn't load texture 'textures/shadow01.png': Unable to open file, blacklisting
[ERROR]: Error opening file with PHYSFS: "textures/shadow02.png"
[ERROR]: Couldn't load texture 'textures/shadow02.png': Unable to open file, blacklisting
[ERROR]: Error opening file with PHYSFS: "textures/shadow03.png"
[ERROR]: Couldn't load texture 'textures/shadow03.png': Unable to open file, blacklisting
[ERROR]: Error opening file with PHYSFS: "textures/shadow04.png"
[ERROR]: Couldn't load texture 'textures/shadow04.png': Unable to open file, blacklisting
[ERROR]: Error opening file with PHYSFS: "textures/shadow05.png"
[ERROR]: Couldn't load texture 'textures/shadow05.png': Unable to open file, blacklisting
[ERROR]: Error opening file with PHYSFS: "textures/shadow06.png"
[ERROR]: Couldn't load texture 'textures/shadow06.png': Unable to open file, blacklisting
[ERROR]: Error opening file with PHYSFS: "textures/shadow07.png"
[ERROR]: Couldn't load texture 'textures/shadow07.png': Unable to open file, blacklisting
[ERROR]: Error opening file with PHYSFS: "textures/shadow08.png"
[ERROR]: Couldn't load texture 'textures/shadow08.png': Unable to open file, blacklisting
[ERROR]: Error opening file with PHYSFS: "textures/shadow09.png"
[ERROR]: Couldn't load texture 'textures/shadow09.png': Unable to open file, blacklisting
[ERROR]: Error opening file with PHYSFS: "textures/shadow10.png"
[ERROR]: Couldn't load texture 'textures/shadow10.png': Unable to open file, blacklisting
[ERROR]: Error opening file with PHYSFS: "textures/shadow11.png"
[ERROR]: Couldn't load texture 'textures/shadow11.png': Unable to open file, blacklisting
[ERROR]: Error opening file with PHYSFS: "textures/shadow12.png"
[ERROR]: Couldn't load texture 'textures/shadow12.png': Unable to open file, blacklisting
[ERROR]: Error opening file with PHYSFS: "textures/shadow13.png"
[ERROR]: Couldn't load texture 'textures/shadow13.png': Unable to open file, blacklisting
[ERROR]: Error opening file with PHYSFS: "textures/shadow14.png"
[ERROR]: Couldn't load texture 'textures/shadow14.png': Unable to open file, blacklisting
[ERROR]: Error opening file with PHYSFS: "textures/shadow15.png"
[ERROR]: Couldn't load texture 'textures/shadow15.png': Unable to open file, blacklisting
[ERROR]: Error opening file with PHYSFS: "textures/dirty05.png"
[ERROR]: Couldn't load texture 'textures/dirty05.png': Unable to open file, blacklisting

**Comment by badernageral** [comment]
Hi @CozmoCyke, this error happens even in official missions, but they work just as you can see, if any problems happen, please let me know.

**Comment by CozmoCyke** [comment]
True ! The problem with these errors doesn't come from your missions :-(
I have opened an issue on Github on the official project Colobot.
https://github.com/colobot/colobot/issues/1283

**Comment by CozmoCyke** [comment]
The issue doesn't come from colobot-logic !
