### ISSUE TITLE
Missing solutions to chapter 1-5

### ISSUE THREAD

**Issue by CozmoCyke** [badernageral/colobot-logic#4]
Hello ,

Thanks for these lessons. I'm going to translate them in French.
Where can I find the msolu.txt (solution examples to each exercise) ?

**Comment by badernageral** [comment]
Hi @CozmoCyke, I had not done any solutions, but now i coded it and just commited to the repository, you can download the missions with them.
If you translate the missions, make a pull request, is a big help, thanks.

**Comment by CozmoCyke** [comment]
Hello @badernageral , 
Thank you very much for your solutions :-)
Now I have to copy them to French and pull a request !
